// generated with sea-orm-cli generate entity -u "sqlite:./../tg_eye_stats.sqlite3" -o src/entities

//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub mod prelude;

pub mod user_info;
pub mod user_status;
