//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_info")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub telegram_user_id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub full_name: Option<String>,
    #[sea_orm(column_type = "Blob", nullable)]
    pub profile_photo: Option<Vec<u8>>,
    #[sea_orm(column_type = "Text", nullable)]
    pub username: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
